
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: my-otelcol
  namespace: guardrails-test
  resourceVersion: '123351950'
  uid: 3f447f07-9c98-4f33-ae73-96e5e2d9e156
spec:
  observability:
    metrics: {}
  deploymentUpdateStrategy: {}
  config:
    connectors:
      spanmetrics:
        metrics_flush_interval: 15s
    exporters:
      debug: {}
      otlp:
        endpoint: 'my-jaeger-collector-headless.guardrails-test.svc.cluster.local:14250'
        tls:
          ca_file: /etc/pki/ca-trust/source/service-ca/service-ca.crt
      prometheus:
        add_metric_suffixes: false
        endpoint: '0.0.0.0:8889'
        resource_to_telemetry_conversion:
          enabled: true
    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: '0.0.0.0:4317'
          http:
            endpoint: '0.0.0.0:4318'
    service:
      pipelines:
        metrics:
          exporters:
            - debug
            - prometheus
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
            - spanmetrics
        traces:
          exporters:
            - debug
            - otlp
            - spanmetrics
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
  mode: deployment
  volumeMounts:
    - mountPath: /etc/pki/ca-trust/source/service-ca
      name: cabundle-volume
  volumes:
    - configMap:
        name: my-otelcol-cabundle
      name: cabundle-volume
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: '2025-08-08T14:05:26Z'
  generation: 8
  labels:
    release: prometheus
  managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:release': {}
        'f:spec':
          .: {}
          'f:endpoints': {}
          'f:selector': {}
      manager: Mozilla
      operation: Update
      time: '2025-08-08T17:27:42Z'
  name: otel-tls-sm
  namespace: guardrails-test
  resourceVersion: '123354683'
  uid: 9ed3da33-a721-4a70-9992-d4aa7ac7e012
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: prometheus
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: guardrails-test.my-otelcol-tls
      app.kubernetes.io/managed-by: opentelemetry-operator
      app.kubernetes.io/part-of: opentelemetry
