apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: fms-otel-collector-servicemonitor
  namespace: guardrails-test
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: prometheus
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: guardrails-test.fms-otel-collector
      app.kubernetes.io/managed-by: opentelemetry-operator
      app.kubernetes.io/part-of: opentelemetry
